# Generated by Django 5.2.4 on 2025-11-24 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        # Add a temporary FK field 'subject_temp', populate it from existing char field,
        # then remove old 'subject' char field and rename temp to 'subject'. This preserves
        # existing subject text values by creating Subject rows.
        migrations.AddField(
            model_name='group',
            name='subject_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.subject'),
        ),

        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda Group, Subject, Branch: [
                    (lambda g, name: (
                        (lambda subj: (setattr(g, 'subject_temp_id', subj.id), g.save(update_fields=['subject_temp']))[0])
                        if name else None
                    )(
                        Subject.objects.get_or_create(
                            name=name,
                            organization_id=(Branch.objects.filter(id=g.branch_id).first().organization_id if getattr(g, 'branch_id', None) else None)
                        )[0]
                    ))(g, getattr(g, 'subject', None))
                    for g in Group.objects.all()
                ])
            )(
                apps.get_model('core', 'Group'),
                apps.get_model('core', 'Subject'),
                apps.get_model('core', 'Branch')
            ),
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),

        migrations.RenameField(
            model_name='group',
            old_name='subject_temp',
            new_name='subject',
        ),
    ]
