# Generated by Django 5.2.8 on 2025-11-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_subject_room_group_room_roomschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
