# Generated by Django 5.2.8 on 2025-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_course_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('days__overlap', True)), fields=('room', 'start_time', 'end_time'), name='unique_room_schedule'),
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='day',
        ),
    ]
