# Generated by Django 5.2.4 on 2025-11-24 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_customuser_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('min_purchase_for_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_branch', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loyalty_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_branches', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='loyalty.loyaltybranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('loyalty_branch', 'user')},
            },
        ),
    ]
